version: "3.3"
services:
    tests:
        build:
            context: .
            dockerfile: Dockerfile.tests
        environment: 
            - HOSTNAME=master

networks: 
        default: 
                external: 
                    name: compose-network
