version: "3.9"
services:
  tester:
    build:
      context: .
      dockerfile: Dockerfile.tests
    network_mode: bridge 
    environment:
      - IP_ADDRESS_API=${IP_ADDR}

networks: 
  default: 
    external: 
      name: external-network