name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create network
        run: docker network create compose-network
      - name: Build the stack
        run: docker-compose up --build -d
      - name: Build the stack
        run: docker-compose -f docker-compose.tests.yml up --build 
      - name: Print tests
        run: docker logs compose-ci-cd_tester_1

    
