name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up --build -d
      - name: Get the IP of the container
        run: echo "IP_ADDR=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}'  compose-ci-cd_master_1)" >> $GITHUB_ENV
      - name: Test
        run: echo $IP_ADDR
      - name: Build the stack
        run: docker-compose -f docker-compose.tests.yml up --build -d
      - name: Print tests
        run: docker logs compose-ci-cd_tester_1

    